// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "confluent.type.Decimal")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Decimal {
    /// The two's-complement representation of the unscaled integer value in big-endian byte order
    #[prost(bytes = "vec", tag = "1")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// The precision
    #[prost(uint32, tag = "2")]
    pub precision: u32,
    /// The scale
    #[prost(int32, tag = "3")]
    pub scale: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "confluent.type.Variant")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Variant {
    /// A dictionary of field names used by all objects in the variant value.
    /// Encoded as: version header, dictionary size, offset list, and UTF-8 string data.
    #[prost(bytes = "vec", tag = "1")]
    pub metadata: ::prost::alloc::vec::Vec<u8>,
    /// The variant value, which can be a primitive, object, or array.
    /// Encoded as: a one-byte header (basic type + type info) followed by the content bytes.
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
