// This file is @generated by prost-build.
/// C1/C2: inline rules at message and field level, all expected to PASS.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "parity.ParityRecord")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParityRecord {
    #[prost(message, optional, tag = "1")]
    pub amount: ::core::option::Option<super::confluent::r#type::Decimal>,
    #[prost(message, optional, tag = "2")]
    pub ts: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<super::confluent::r#type::Variant>,
    #[prost(string, tag = "4")]
    pub plain: ::prost::alloc::string::String,
}
/// The must-fail twin: every rule inverted. A correct client reports 6 violations.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "parity.ParityRecordN")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParityRecordN {
    #[prost(message, optional, tag = "1")]
    pub amount: ::core::option::Option<super::confluent::r#type::Decimal>,
    #[prost(message, optional, tag = "2")]
    pub ts: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<super::confluent::r#type::Variant>,
    #[prost(string, tag = "4")]
    pub plain: ::prost::alloc::string::String,
}
/// No inline rules: used for the domain-rule capabilities C3-C7.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "parity.ParityPlain")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParityPlain {
    #[prost(message, optional, tag = "1")]
    pub amount: ::core::option::Option<super::confluent::r#type::Decimal>,
    #[prost(message, optional, tag = "2")]
    pub ts: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<super::confluent::r#type::Variant>,
    #[prost(string, tag = "4")]
    pub plain: ::prost::alloc::string::String,
}
