// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "test.ValidationAddress")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationAddress {
    #[prost(string, tag = "1")]
    pub zip: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "test.ValidationOrder")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationOrder {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub quantity: i32,
    /// A field-level rule on a repeated or map field is evaluated once, with the whole
    /// collection bound to `this`, so a rule about the elements is written as a
    /// comprehension over them.
    #[prost(string, repeated, tag = "3")]
    pub items: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub address: ::core::option::Option<ValidationAddress>,
    #[prost(map = "string, int32", tag = "5")]
    pub scores: ::std::collections::HashMap<::prost::alloc::string::String, i32>,
    /// Exercises the unsigned conversion: a value above int64 max must still compare as
    /// positive, which it would not if it were narrowed to a signed integer.
    #[prost(uint64, tag = "6")]
    pub serial: u64,
}
/// A `has()` written inside a comprehension is rooted at the comprehension's own variable
/// rather than at `this`, so the presence prescan has to follow that variable back to the
/// path of the collection it iterates. Both shapes an element can be reached through are
/// here: a repeated field and the values of a map.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "test.ValidationChild")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationChild {
    /// Explicit presence, which is the case a comprehension used to get wrong: the field was
    /// omitted whenever unset before the prescan, and always present after it.
    #[prost(string, optional, tag = "1")]
    pub nickname: ::core::option::Option<::prost::alloc::string::String>,
    /// Implicit presence: unset means equal to the default.
    #[prost(int32, tag = "2")]
    pub count: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "test.ValidationParent")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationParent {
    #[prost(message, repeated, tag = "1")]
    pub children: ::prost::alloc::vec::Vec<ValidationChild>,
    #[prost(map = "string, message", tag = "2")]
    pub by_name: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ValidationChild,
    >,
    #[prost(message, optional, tag = "3")]
    pub only: ::core::option::Option<ValidationChild>,
}
/// A well-known type stands for the thing it wraps, not a message with a `value` field: a
/// StringValue is a string and an Int64Value is an int. Without unwrapping, `size(this)` has
/// no overload for a message and a rule would have to read `this.value` in this client alone.
/// Timestamp and Duration are covered by a unit test instead: prost maps them to
/// prost_types, which does not implement the serde derives applied to generated code here.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "test.ValidationWellKnown")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationWellKnown {
    #[prost(message, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "2")]
    pub count: ::core::option::Option<i64>,
    #[prost(message, optional, tag = "3")]
    pub active: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "4")]
    pub big: ::core::option::Option<u64>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "test.TestMessage")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestMessage {
    #[prost(string, tag = "1")]
    pub test_string: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub test_bool: bool,
    #[prost(bytes = "vec", tag = "3")]
    pub test_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(double, tag = "4")]
    pub test_double: f64,
    #[prost(float, tag = "5")]
    pub test_float: f32,
    #[prost(fixed32, tag = "6")]
    pub test_fixed32: u32,
    #[prost(fixed64, tag = "7")]
    pub test_fixed64: u64,
    #[prost(int32, tag = "8")]
    pub test_int32: i32,
    #[prost(int64, tag = "9")]
    pub test_int64: i64,
    #[prost(sfixed32, tag = "10")]
    pub test_sfixed32: i32,
    #[prost(sfixed64, tag = "11")]
    pub test_sfixed64: i64,
    #[prost(sint32, tag = "12")]
    pub test_sint32: i32,
    #[prost(sint64, tag = "13")]
    pub test_sint64: i64,
    #[prost(uint32, tag = "14")]
    pub test_uint32: u32,
    #[prost(uint64, tag = "15")]
    pub test_uint64: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "test.DependencyMessage")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DependencyMessage {
    #[prost(bool, tag = "1")]
    pub is_active: bool,
    #[prost(message, optional, tag = "2")]
    pub test_message: ::core::option::Option<TestMessage>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "test.Author")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Author {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub id: i32,
    #[prost(bytes = "vec", tag = "3")]
    pub picture: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, repeated, tag = "4")]
    pub works: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(oneof = "author::PiiOneof", tags = "5, 6")]
    pub pii_oneof: ::core::option::Option<author::PiiOneof>,
}
/// Nested message and enum types in `Author`.
pub mod author {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum PiiOneof {
        #[prost(message, tag = "5")]
        OneofMessage(super::Pizza),
        #[prost(string, tag = "6")]
        OneofString(::prost::alloc::string::String),
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "test.Pizza")]
#[prost_reflect(descriptor_pool = "crate::TEST_DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pizza {
    #[prost(string, tag = "1")]
    pub size: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub toppings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
