// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(::prost_reflect::ReflectMessage)]
#[prost_reflect(message_name = "confluent.type.Decimal")]
#[prost_reflect(descriptor_pool = "crate::DESCRIPTOR_POOL")]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Decimal {
    /// The two's-complement representation of the unscaled integer value in big-endian byte order
    #[prost(bytes = "vec", tag = "1")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// The precision
    #[prost(uint32, tag = "2")]
    pub precision: u32,
    /// The scale
    #[prost(int32, tag = "3")]
    pub scale: i32,
}
