name: CI 
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROTOC_VERSION: '3.25.3'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Rust Format
        run: cargo fmt --all -- --check

      - name: Rust Build
        run: export PROTOC=/usr/bin/protoc && cargo build --all-features

      - name: Rust Test
        run: RUST_BACKTRACE=1 cargo test --all-features
